apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: "15s"
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToMetrics:
        datasourceUid: prometheus
      tracesToLogsV2:
        datasourceUid: opensearch
        filterByTraceID: true

  - name: OpenSearch
    type: grafana-opensearch-datasource
    uid: opensearch
    access: proxy
    url: http://opensearch:9200
    jsonData:
      flavor: OpenSearch
      version: "2.11.0"
      timeField: "@timestamp"
