package com.alper.backend.admin.model;

public enum AuditAction {
    USER_ROLE_CHANGED,
    USER_STATUS_CHANGED,
    USER_2FA_RESET,
    USER_FORCE_LOGGED_OUT,
    SOURCE_CREATED,
    SOURCE_UPDATED,
    SOURCE_DELETED,
    SOURCE_TOGGLED,
    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED,
    NEWS_CATEGORY_OVERRIDDEN,
    NEWS_STATUS_CHANGED,
    NEWS_FETCH_TRIGGERED,
    SCHEDULER_JOB_TOGGLED,
    SCHEDULER_JOB_TRIGGERED,
    BACKFILL_TRIGGERED,
    TRADE_MANUALLY_APPROVED,
    TRADE_MANUALLY_REJECTED
}